### ISSUE TITLE
git : fatal: not a git repository 

### ISSUE THREAD

**Issue by devmiyax** [k3rn31p4nic/appveyor-discord-webhook#13]
Hi, 

Fast of all, thank you for your beautiful script. But In my environment it does not work with this error message. Can you help?

```
git : fatal: not a git repository (or any of the parent directories): .git
At C:\projects\yabause\yabause\build\send.ps1:38 char:17
+ ... UTHOR_NAME="$(git log -1 "$env:APPVEYOR_REPO_COMMIT" --pretty="%aN")"
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (fatal: not a gi...ectories): .git:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
git : fatal: not a git repository (or any of the parent directories): .git
```
Entire log is here.
https://ci.appveyor.com/project/devmiyax/yabause/builds/30049653#L2013

Source code is here.
https://github.com/devmiyax/yabause/blob/appveyor_again/appveyor.yml#L131

**Comment by iamtraction** [comment]
For some reason it's not being recognized as a git repo. It shouldn't be happening unless you're running it outside the build directory. Are you moving out of your directory before running the script?

**Comment by iamtraction** [comment]
Closing this issue, as there's no response from the author. If you're still facing this issue, feel free to reopen it with more details.
