### ISSUE TITLE
Update links to repo

### ISSUE THREAD

**Issue by iamtraction** [k3rn31p4nic/appveyor-discord-webhook#5]
Since this repo is now moved to the [DiscordHooks](https://github.com/DiscordHooks) org., we should now update all the links in this repo from `k3rn31p4nic/appveyor-discord-webhook` to `DiscordHooks/appveyor-discord-webhook`.

*PRs are welcome.*

**Comment by soulspark666** [comment]
I'll do something about it.

**Comment by soulspark666** [comment]
Will the author be k3rn31p4nic or DiscordHooks?
